server:
  port: 8080

spring:
  application:
    name: fx-rate-hub
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0

app:
  rabbitmq:
    rate-input-queue: rate.input.queue
  rate:
    spread-alarm-threshold: ${SPREAD_ALARM_THRESHOLD:0.0010}
  hazelcast:
    cluster-name: ${HAZELCAST_CLUSTER_NAME:fx-rate-cluster}
    address: ${HAZELCAST_ADDRESS:localhost:5701}
  producer:
    enabled: ${RATE_PRODUCER_ENABLED:false}
    interval-ms: ${RATE_PRODUCER_INTERVAL_MS:1000}
    pairs:
      - EUR/USD
      - USD/TRY
      - GBP/USD

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.fxrate.platform: DEBUG
